version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./org-files:/app/org-files
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true